config/routes.rb
Rails.application.routes.draw do
  namespace :user do
  get 'oauths/oauth'
  end

  namespace :user do
  get 'oauths/callback'
  end

  resources :challenges

  namespace :users, as: :user do
    resource :registration, only: [:new, :create]
    resource :session, only: [:new, :create, :destroy]
    get :activate, controller: 'registrations', action: 'activate'

    post "oauth/callback" => "oauths#callback"
    get "oauth/callback" => "oauths#callback"
    get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

    resource :profile, only: [:show] do
      get :edit, on: :collection
      patch :update, on: :collection
    end
  end

  delete 'logout' => 'users/sessions#destroy', :as => :logout
  get 'challenge' => 'home#challenge', as: :current_challenge

  root to: 'home#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	belongs_to :user

	scope :completed, -> { where.not(content: nil) }

	before_save on: :create do
		self.started_at = Time.now
	end

	def display_title
		title || words.join(", ")
	end
end

app/models/challenge_level.rb
class ChallengeLevel < OpenStruct
	include ActiveModel::Model
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :old_password
	
	authenticates_with_sorcery! do |config|
		config.authentications_class = Authentication
	end

	has_many :authentications, :dependent => :destroy
	accepts_nested_attributes_for :authentications

	validates :password, confirmation: true

	has_many :challenges

	def current_challenge
		challenges.where(["started_at + (time_limit * interval '1 minutes') > ?", Time.now]).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	def new
		redirect_to current_challenge_path if current_user.current_challenge

		@challenge_levels = [:express, :normal, :storyteller, :skald].map do |level|
			level_params = ChallengeLevelService.new(level).call
			level_params[:words] = level_params[:words].length
			level_params[:name] = t('levels.' + level.to_s)
			level_params[:internal_name] = level

			ChallengeLevel.new.tap do |cl|
				level_params.each {|k,v| cl.send("#{k}=", v)}
			end
		end
	end

	def index
		@challenges = Challenge.completed
	end

	def create
		redirect_to current_challenge_path if current_user.current_challenge
		
		# TODO: add error handling
		parameters = ChallengeLevelService.new(params[:challenge_level][:internal_name]).call
		@challenge = current_user.challenges.create!(parameters)
		redirect_to current_challenge_path
	end

	def update
		@challenge = Challenge.find(params[:id])
		if @challenge.update_attributes!(safe_params)
			render json: {url: challenge_path(@challenge)}
		else
			render @challenge.errors.to_json, status: 422
		end
	end

	def show
		@challenge = Challenge.find(params[:id])
	end

	private
	def safe_params
		params.require(:challenge).permit(:content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@latest_challenges = Challenge.completed.order(started_at: :desc).limit(10).includes(:user)
	end

	def challenge
		@challenge = current_user.current_challenge
		redirect_to new_challenge_path if @challenge.nil?
	end
end

app/controllers/users/oauths_controller.rb
class Users::OauthsController < ApplicationController
	skip_before_filter :require_login

	# sends the user on a trip to the provider,
	# and after authorizing there back to the callback url.
	def oauth
		login_at(params[:provider])
	end

	def callback
		provider = params[:provider]
		if @user = login_from(provider)
			redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
		else
			begin
				@user = create_from(provider)
				# NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

				reset_session # protect from session fixation attack
				auto_login(@user)
				redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
			# rescue
			# 	redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
			end
		end
	end

	#example for Rails 4: add private method below and use "auth_params[:provider]" in place of 
	#"params[:provider] above.

	private
	def auth_params
		params.permit(:code, :provider)
	end

end

app/controllers/users/profiles_controller.rb
module Users
	class ProfilesController < ApplicationController
		def edit
			@user = current_user
		end

		def update
			@user = current_user
			passwords = strip_password_params
			if passwords.length > 0
				unless User.authenticate(@user.email, passwords[:old])
					flash[:error] = 'Niepoprawne hasło'
					render action: :edit and return
				end

				@user.password = passwords[:new]
				@user.password_confirmation = passwords[:confirmation]
			end

			@user.name = safe_params[:name]

			if @user.save
				redirect_to :root
			else
				render :edit
			end
		end

		private
		def safe_params
			params.require(:user).permit(:name)
		end

		def strip_password_params
			{
				old: params[:user].delete(:old_password),
				new: params[:user].delete(:password),
				confirmation: params[:user].delete(:password_confirmation)
			}.reject{|k,v| v.blank?}
		end
	end
end

app/controllers/users/registrations_controller.rb
module Users
	class RegistrationsController < ApplicationController
		def new
			@user = User.new
		end

		def create
			@user = User.new(safe_params)
			@user.save!
			@user.activate! # for now
			redirect_to :root
		end

		def activate
			if (@user = User.load_from_activation_token(params[:token]))
				@user.activate!
				redirect_to(new_user_session_path, :notice => 'User was successfully activated.')
			else
				not_authenticated
			end
		end

		private
		def safe_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
	end
end

app/controllers/users/sessions_controller.rb
module Users
	class SessionsController < ApplicationController
		def new
			@user = User.new
			redirect_to :root if logged_in?
		end

		def create
			if @user = login(params[:user][:email], params[:user][:password])
				redirect_back_or_to(:root, notice: 'Login successful')
			else
				@user = User.new
				flash.now[:alert] = 'Login failed'
				redirect_to action: 'new'
			end
		end

		def destroy
			logout
			redirect_to(:root, notice: 'Logged out!')
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/index.html.haml
%h1 Wyzwania

%ul
	- @challenges.each do |challenge|
		%li= link_to challenge.display_title, challenge

app/views/challenges/new.html.haml
.row
	- @challenge_levels.each do |level|
		.col-md-3
			= simple_form_for level, url: challenges_path, class: 'challenge-level' do |f|
				%h3= level.name
				%ul
					%li Minimum #{level.target_word_count} słów
					%li #{level.time_limit} minut
					%li Losowanych słów: #{level.words}
				= f.input :internal_name, as: :hidden
				= f.button :submit, value: 'Stwórz mi wyzwanie'

app/views/challenges/show.html.haml
.row
	.col-md-9
		%h1= @challenge.words.join(", ")

		.challenge-body
			%p= simple_format @challenge.content

app/views/home/challenge.html.erb
<div class="container-fluid challenge-container" 
    ng-app="challenge" ng-controller="TextController as textCtrl" ng-init="textCtrl.setUrl('<%= challenge_path(@challenge.id) %>')">
  <div class="panel">
    <div class="panel-heading challenge-stats">
      <div class="pull-right">
        <span class="label label-default" ng-bind="textCtrl.challenge.time_left | timeLeft"></span>
      </div>
      <p><span class="label label-default" ng-class="textCtrl.wordCountMet() ? 'label-success' : 'label-warning'">Liczba słów: {{textCtrl.word_count}} / {{textCtrl.challenge.target_word_count }}</span></p>
      <p class="words">
        <span class="label label-default" ng-class="textCtrl.wordInContent(word) ? 'label-success' : 'label-warning'" ng-repeat="word in textCtrl.challenge.words">{{ word }}</span>
      </p>
    </div>
    <div class="panel-body">
      <div class="alert alert-danger" role="alert" ng-show="textCtrl.failed_attempt">
        Niestety, tym razem nie udało Ci się sprostać wyzwaniu. Nie poddawaj się jednak. Powodzenia w przyszłości!<br/>
        <%= link_to 'Daj mi nowe wyzwanie', new_challenge_path %>.
      </div>
      <form class="form-horizontal" action="<%= challenge_path(@challenge.id) %>" ng-submit="textCtrl.onFormSubmit($event)">
        <div class="form-group">
          <textarea class="form-control challenge-input" autofocus 
            ng-model="textCtrl.content" ng-change="textCtrl.contentUpdated()" ng-disabled="textCtrl.failed_attempt"
            id="challenge_content" name="challenge[content]">
              {{text.content}}
            </textarea>
        </div>
        <button ng-show="textCtrl.isValid()" class="btn btn-success">Wyślij</button>
      </form>
    </div>
  </div>
</div>

<%= content_for :head do %>
  <script>
    window.challenge = <%=raw @challenge.to_json %>;
    window.challenge.time_left = <%= (@challenge.started_at + @challenge.time_limit.minutes - Time.now).to_i %>;
  </script>
<%- end -%>

app/views/home/index.html.haml
.row
	.col-md-12
		.jumbotron.center.cta
			%h1 Podejmij wyzwanie!
			- if logged_in?
				= link_to 'Rozpocznij wyzwanie', new_challenge_path, class: 'btn btn-success'
			- else
				= link_to 'Zarejestruj się', new_user_registration_path, class: 'btn btn-info'
				= link_to 'Zaloguj się', new_user_session_path, class: 'btn btn-info'
				= link_to 'Zaloguj się Facebookiem', user_auth_at_provider_path(:provider => :facebook), class: 'btn btn-info'
		.second-line
			.row
				.col-md-6
					%h2.center O co chodzi?

					.justify
						:markdown
							Wyzwanie pisarskie jest proste (choć nie znaczy to, że łatwe). Otrzymujesz określoną liczbę słów oraz limit czasowy. Musisz stworzyć krótkie opowiadanie, które będzie zawierać zadanie Ci słowa oraz zmieścić się w limicie czasowym. Jeśli Ci się uda, Twoja praca zostanie zapisana. Jeśli nie, stracisz ją.

							Pamiętaj, że musisz użyć słów w dokładnie takiej formie, w jakiej zostały zadane.
				.col-md-6
					%h2.center Najnowsze wyzwania

					%ul
						- @latest_challenges.each do |challenge|
							%li
								= link_to challenge.display_title, challenge
								by
								= challenge.user.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WritingChallenge</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= csrf_meta_tags %>
	<%= yield :head %>
	<script type="text/javascript">
		WebFontConfig = {
			google: { families: [ 'Lato::latin,latin-ext' ] }
		};
		(function() {
			var wf = document.createElement('script');
			wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
				'://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
			wf.type = 'text/javascript';
			wf.async = 'true';
			var s = document.getElementsByTagName('script')[0];
			s.parentNode.insertBefore(wf, s);
		})(); </script>
</head>
<body>
<%= render partial: 'shared/navbar' %>
<div class="row main-container">
	<div class="col-md-12">
		<% flash.each do |key, val| %>
			<div class="alert"><%= val %></div>
		<% end -%>
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Wyzwanie pisarskie</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Wyzwania', challenges_path %></li>
        <%- if logged_in? %>
        <li><%= link_to 'Edytuj profil', edit_user_profile_path %></li>
        <li><%= link_to 'Wyloguj', logout_path, method: :delete %></li>
        <%- else -%>
        <li><%= link_to 'Zaloguj', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/oauths/callback.html.erb
<h1>User::Oauths#callback</h1>
<p>Find me in app/views/user/oauths/callback.html.erb</p>

app/views/users/oauths/oauth.html.erb
<h1>User::Oauths#oauth</h1>
<p>Find me in app/views/user/oauths/oauth.html.erb</p>

app/views/users/profiles/edit.html.haml
= simple_form_for @user, url: user_profile_path do |f|

	.row
		.col-md-6
			= f.input :name

		.col-md-6
			%h4 Pozostaw puste, jeśli nie chcesz zmieniać
			= f.input :old_password
			= f.input :password
			= f.input :password_confirmation

	= f.button :submit, value: 'Zapisz profil'